name: OIDC Debug

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  debug:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Request OIDC Token
        shell: bash
        run: |
          echo "Requesting OIDC token..."

          RESPONSE=$(curl -s \
          -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
          "${ACTIONS_ID_TOKEN_REQUEST_URL}&audience=jfrog-github")

          echo "Raw response:"
          echo "$RESPONSE"

          TOKEN=$(echo "$RESPONSE" | jq -r '.value')

          if [ "$TOKEN" = "null" ]; then
            echo "Failed to obtain token"
            exit 1
          fi

          echo ""
          echo "Token successfully obtained."
          echo "Token length: ${#TOKEN}"

      - name: Exchange JWT for JFrog Token
      shell: bash
      run: |
        RESPONSE=$(curl -s \
          -X POST \
          https://pataclick.jfrog.io/access/api/v1/oidc/token \
          -H "Content-Type: application/json" \
          -d "{
              \"grant_type\":\"urn:ietf:params:oauth:grant-type:token-exchange\",
              \"subject_token_type\":\"urn:ietf:params:oauth:token-type:id_token\",
              \"subject_token\":\"$TOKEN\",
              \"provider_name\":\"github-jfrog-oidc\"
          }")

          echo "===== JFROG RESPONSE ====="
          echo "$RESPONSE"
